name: push-to-docker

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Build Image
        run: docker build . -- tag $IMAGE_NAME

      - name: Log in to docker hub
        run: echo "{{ secrets.ACCESS_TOKEN }}" | docker login -u keriteal --password-stdin

      - name: Push image
        run: |
          IMAGE_ID = keriteal/$IMAGE_NAME
          IMAGE_ID = $(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
